### ISSUE TITLE
Icon "Paste" after smartphone is put to sleep

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-mobile#92]
Steps:

1. Run the program.
2. Put your smartphone to sleep.
3. Wake up the smartphone.

The "Paste" icon is inactive after waking up the smartphone (maybe an empty clipboard lock is working).

Before sleep:

![obraz](https://user-images.githubusercontent.com/47037905/134638086-b9601e97-bc3f-4875-9a65-918709f8992c.png)

After sleep:

![obraz](https://user-images.githubusercontent.com/47037905/134638265-38958335-1fa5-429f-8036-ff294a3f29c7.png)

**Comment by ManeraKai** [comment]
Even if you put it in background. Same thing happens.

**Comment by ManeraKai** [comment]
It's really weird. Here I'm printing the clipboard data every resume of the app. It's giving me null:
![image](https://user-images.githubusercontent.com/40805353/134641791-cd434405-a6a5-4f18-8937-08acb0c86c70.png)

**Comment by ManeraKai** [comment]
But if I let it be on for the whole time. The paste function works inside the paste widget.

**Comment by ManeraKai** [comment]
If closed automatically, If you found any problem. You can open it. I've tested it on the emulator and my real device. Worked quietly.

**Comment by Valdnet** [comment]
In the new version, the behavior of the "Paste" icon is now as follows: If the clipboard is empty, then after the smartphone is put to sleep or when it is running in the background, the "Paste" icon becomes active.

**Comment by ManeraKai** [comment]
This is happening to me in the real device too. I think it should just be active all the time. It really doesn't hurt the user. I wish it was responsive, but I tried.

**Comment by Valdnet** [comment]
> It really doesn't hurt the user.

Hehe, but it hurts the reputation of the application 😁.

Let you leave this issue open. Maybe you will find some more solution.

**Comment by Valdnet** [comment]
Closed for issue #96.

**Comment by ManeraKai** [comment]
Try it: https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1302530551

**Comment by Valdnet** [comment]
When you put your smartphone to sleep with the contents of the clipboard, the "Paste" icon is inactive.

**Comment by ManeraKai** [comment]
When I switch between apps, it pauses the app and resumes it when opened back. However, sleeping or locking the phone weirdly empties the clipboard. I'll try to find a workaround like waiting some seconds before checking.

**Comment by ManeraKai** [comment]
Try it: https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1302685724

**Comment by Valdnet** [comment]
Now it works fine 👍.
